version: '3.1'

volumes:
    grafana_data: {}
    influx_data: {}
    
services:

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 80:3000
    links:
      - influxdb
    volumes:
      # Makes sure data is stored in host only if 
      # postgres is still not configured in the grafana.env file
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  connector:
    container_name: connector
    image: encresearch/mqtt-connector:latest
    restart: unless-stopped

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      # Data persistency
      - influx_data:/var/lib/influxdb
    restart: unless-stopped

  telegraf: # Sends metric reports about the host
    container_name: telegraf
    image: telegraf
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    hostname: dev-server
    links:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  watchtower: # checks for changes in any of the installed images (on the latest tag)
  container_name: watchtower
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # mounts docker socket to interact with Docker's API
    command: --interval 300 # Checks for changes every 5 minutes
    restart: unless-stopped